version: '3.8'


services:
  
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
    

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  mongo:
    image: mongo:6
    container_name: mongo
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  mongo-init:
    image: mongo:6
    depends_on:
      - mongo
    entrypoint:
      [
        "bash",
        "-c",
        "sleep 5 && mongosh --host mongo --eval 'rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"mongo:27017\" }]})'"
      ]
  auth-ms:
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
      - mongo-init

volumes:
  mongo_data:

#   products-ms:
#     build: ./products-ms
#     volumes:
#       - ./products-ms/src:/usr/src/app/src
#     command: npm run start:dev
#     environment:
#       - PORT=3001
#       - NATS_SERVERS=nats://nats-server:4222
#       - DATABASE_URL=file:./dev.db

  
#   # Orders MS
#   orders-ms:
#     depends_on:
#       - orders-db
#     build: ./orders-ms
#     volumes:
#       - ./orders-ms/src:/usr/src/app/src
#     command: npm run start:dev
#     environment:
#       - PORT=3002
#       - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public
#       - NATS_SERVERS=nats://nats-server:4222



#   # Orders DB
#   orders-db:
#     container_name: orders_database
#     image: postgres:16.2
#     restart: always
#     volumes:
#       - ./orders-ms/postgres:/var/lib/postgresql/data
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=123456
#       - POSTGRES_DB=ordersdb

# # ======================
# # Payments Microservice
# # ======================
#   payments-ms:
#     container_name: payments-ms
#     build: ./payments-ms
#     volumes:
#       - ./payments-ms/src:/usr/src/app/src
#     command: npm run start:dev
#     ports:
#       - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
#     environment:
#       - PORT=${PAYMENTS_MS_PORT}
#       - NATS_SERVERS=nats://nats-server:4222
#       - STRIPE_SECRET=${STRIPE_SECRET}
#       - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
#       - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
#       - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      